// bde-search-nuxt/app/app.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import products from "../top-1000-products.json";

// set the reactive variable
const userSearchQuery = ref("");

// Filter products based on search query
const productSearchResults = computed(() => {
  if (!userSearchQuery.value) return [];
  return products.filter((product) =>
    product.name.toLowerCase().includes(userSearchQuery.value.toLowerCase())
  );
});

// List of all unique categories from matching products
const categorySearchResults = computed(() => {
  const categories = productSearchResults.value.map(
    (product) => product.category
  );
  return [...new Set(categories)];
});

// Show the first item in the results as suggestion
const searchSuggestions = computed(() => {
  if (!userSearchQuery.value) return [];

  // Use optional chaining so typescript stops crying
  const firstProductName = productSearchResults.value[0]?.name;
  return firstProductName ? [firstProductName] : [];
});
</script>

<template>
  <div class="container mx-auto p-4">
    <h1 class="text-2xl font-bold text-bde-blue mb-4 text-center">
      Deutschlands beliebter Preisvergleich
    </h1>
    <h3 class="text-center mb-4">Es geht immer billiger.de</h3>

    <input
      v-model="userSearchQuery"
      type="text"
      placeholder="Wonach Suchen Sie?"
      class="w-full p-2 border border-bde-highlight rounded mb-4 focus:outline-none focus:ring-2 focus:ring-bde-orange"
    />

    <div v-if="userSearchQuery">
      <div class="grid grid-cols-2 gap-4">
        <div class="bg-white">
          <h2
            class="uppercase font-bold text-bde-blue mb-2 bg-bde-highlight p-3"
          >
            Produkte
          </h2>
          <ul>
            <!-- Slicing here so we don't display to many entries at once -->
            <li
              v-for="(product, index) in productSearchResults.slice(0, 10)"
              :key="index"
              class="p-2 border-b last:border-none hover:bg-bde-highlight"
            >
              <div>{{ product.name }}</div>
              <div class="text-sm text-gray-600">{{ product.category }}</div>
            </li>
            <!-- {/* In case we don't have any results, display a basic message to the user -->
            <li
              v-if="productSearchResults.length === 0"
              class="p-2 text-gray-500"
            >
              Keine passenden Produkte gefunden.
            </li>
          </ul>
        </div>
        <div class="bg-white">
          <h2
            class="uppercase font-bold text-bde-blue mb-2 bg-bde-highlight p-3"
          >
            Kategorien
          </h2>
          <ul>
            <li
              v-for="(category, index) in categorySearchResults.slice(0, 10)"
              :key="index"
              class="p-2 border-b last:border-none hover:bg-bde-highlight"
            >
              {{ category }}
            </li>
            <li
              v-if="categorySearchResults.length === 0"
              class="p-2 text-gray-500"
            >
              Keine passenden Kategorien
            </li>
          </ul>
        </div>
      </div>
      <div class="bg-white mt-4">
        <h2 class="uppercase font-bold text-bde-blue mb-2 bg-bde-highlight p-3">
          Suchvorschläge
        </h2>
        <ul>
          <li
            v-for="(suggestion, index) in searchSuggestions"
            :key="index"
            class="p-2 border-b last:border-none hover:bg-bde-highlight"
          >
            {{ suggestion }}
          </li>
          <li v-if="searchSuggestions.length === 0" class="p-2 text-gray-500">
            Keine Vorschläge verfügbar
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

// bde-search-react/src/App.tsx
import { useState, ChangeEvent } from "react";
import products from "../src/top-1000-products.json";

export const App = () => {
  // state for user search tracking
  const [userSearchQuery, setUserSearchQuery] = useState("");

  // Filter products based on search query
  const productSearchResults = !userSearchQuery
    ? []
    : products.filter((product) =>
        product.name.toLowerCase().includes(userSearchQuery.toLowerCase())
      );

  // Return an array of unique categories
  const categorySearchResults = Array.from(
    new Set(productSearchResults.map((product) => product.category))
  );

  // Cheap trick to show some type of "Suchvorschlag"
  // If we got products related to the search query, just show the first product as search result
  // Just for the sake of showing something, in a live production I would obviously try to show a more relevant product ;)
  const searchSuggestions = !userSearchQuery
    ? []
    : productSearchResults.length > 0
    ? [productSearchResults[0].name]
    : [];

  // Update the search result whenever the user types something through our setter function
  const handleInputChange = (e: ChangeEvent<HTMLInputElement>) => {
    setUserSearchQuery(e.target.value);
  };

  return (
    <>
      <div className="container mx-auto p-4">
        <h1 className="text-2xl font-bold text-bde-blue mb-4 text-center">
          Deutschlands beliebter Preisvergleich
        </h1>
        <h3 className="text-center mb-4">Es geht immer billiger.de</h3>

        <input
          value={userSearchQuery}
          onChange={handleInputChange}
          type="text"
          placeholder="Wonach Suchen Sie?"
          className="w-full p-2 border border-bde-highlight rounded mb-4 focus:outline-none focus:ring-2 focus:ring-bde-orange"
        />

        {userSearchQuery && (
          <>
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-white">
                <h2 className="uppercase font-bold text-bde-blue mb-2 bg-bde-highlight p-3">
                  Produkte
                </h2>
                <ul>
                  {/* Slicing here so we don't display to many entries at once */}
                  {productSearchResults.slice(0, 10).map((product, index) => (
                    <li
                      key={index}
                      className="p-2 border-b last:border-none hover:bg-bde-highlight"
                    >
                      <div>{product.name}</div>
                      <div className="text-sm text-gray-600">
                        {product.category}
                      </div>
                    </li>
                  ))}
                  {/* In case we don't have any results, display a basic message to the user */}
                  {productSearchResults.length === 0 && (
                    <li className="p-2 text-gray-500">
                      Keine passenden Produkte gefunden.
                    </li>
                  )}
                </ul>
              </div>
              <div className="bg-white">
                <h2 className="uppercase font-bold text-bde-blue mb-2 bg-bde-highlight p-3">
                  Kategorien
                </h2>
                <ul>
                  {categorySearchResults.slice(0, 10).map((category, index) => (
                    <li
                      key={index}
                      className="p-2 border-b last:border-none hover:bg-bde-highlight"
                    >
                      {category}
                    </li>
                  ))}
                  {categorySearchResults.length === 0 && (
                    <li className="p-2 text-gray-500">
                      Keine passenden Kategorien gefunden.
                    </li>
                  )}
                </ul>
              </div>
            </div>
            <div className="bg-white mt-4">
              <h2 className="uppercase font-bold text-bde-blue mb-2 bg-bde-highlight p-3">
                Suchvorschläge
              </h2>
              <ul>
                {searchSuggestions.map((suggestion, index) => (
                  <li
                    key={index}
                    className="p-2 border-b last:border-none hover:bg-bde-highlight"
                  >
                    {suggestion}
                  </li>
                ))}
                {searchSuggestions.length === 0 && (
                  <li className="p-2 text-gray-500">
                    Keine passenden Vorschläge verfügbar.
                  </li>
                )}
              </ul>
            </div>
          </>
        )}
      </div>
    </>
  );
};
